### ISSUE TITLE
instructions for contributing

### ISSUE THREAD

**Issue by Jerimee** [willwulfken/MidJourney-Styles-and-Keywords-Reference#7]
Can you add some basic instructions for what you want/require in a pull request?

Let's say I want to add some artists. Before I submit a PR any special instructions?

**Comment by Squryl** [comment]
Perhaps @willwulfken prefers starting with some [collaborative discussion](https://github.com/willwulfken/MidJourney-Styles-and-Keywords-Reference/discussions/2#discussion-4200926) prior to making pull requests?

**Comment by Jerimee** [comment]
ok I'll close this here and add it there

**Comment by willwulfken** [comment]
I'll write that down in my to do list so that I can hopefully add some instructions later.

Basically at the moment I'm not too picky. Sending a list of styles is okay with me.


If you send images, just make sure to send the prompt format for confirmation.

**For spheres this should be:**
sphere, style --seed 4776

**For "just the style" this should be:**
style --seed 4776

You don't need to do them for every version or anything like that. If I want to add those I will, but you can If you'd like.

If you don't understand the folder structure or categorization, I can always take care of that too. Just try to leave a note about that.
